<?php

namespace Database\Seeders;

use App\Models\TargetTemplate;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TargetTemplateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $templates = [
            [
                'template_id' => 'm42',
                'name' => 'M42 - Grande Nébuleuse d\'Orion',
                'type' => 'Nébuleuse',
                'constellation' => 'Orion',
                'difficulty' => 'beginner',
                'short_description' => 'La plus belle nébuleuse du ciel! Visible même en ville, parfaite pour débuter.',
                'full_description' => 'La Grande Nébuleuse d\'Orion (M42) est l\'une des nébuleuses les plus brillantes et spectaculaires du ciel nocturne. Située à environ 1 350 années-lumière de la Terre, c\'est une véritable pouponnière stellaire où naissent de nouvelles étoiles. Sa luminosité exceptionnelle la rend accessible même depuis les zones urbaines, ce qui en fait une cible idéale pour les débutants en astrophotographie.',
                'tips' => 'Nébuleuse brillante, facile à imager. Essayez différents temps de pose pour éviter la saturation du noyau.',
                'ra_hours' => 5,
                'ra_minutes' => 35,
                'ra_seconds' => 17.3,
                'dec_degrees' => -5,
                'dec_minutes' => 23,
                'dec_seconds' => 28,
                'best_months' => ['Nov', 'Déc', 'Jan', 'Fév', 'Mar'],
                'recommended_shots' => [
                    ['filter_name' => 'L', 'num' => 20, 'exposure' => 120, 'binning' => 1],
                    ['filter_name' => 'R', 'num' => 10, 'exposure' => 120, 'binning' => 1],
                    ['filter_name' => 'G', 'num' => 10, 'exposure' => 120, 'binning' => 1],
                    ['filter_name' => 'B', 'num' => 10, 'exposure' => 120, 'binning' => 1],
                ],
                'estimated_time' => '2h20min',
                'is_active' => true,
                'display_order' => 1,
            ],
            [
                'template_id' => 'm31',
                'name' => 'M31 - Galaxie d\'Andromède',
                'type' => 'Galaxie',
                'constellation' => 'Andromède',
                'difficulty' => 'beginner',
                'short_description' => 'Notre voisine galactique! Immense et spectaculaire.',
                'full_description' => 'La Galaxie d\'Andromède (M31) est la grande galaxie spirale la plus proche de notre Voie Lactée, située à environ 2,5 millions d\'années-lumière. Avec un diamètre de plus de 220 000 années-lumière, elle est plus grande que notre propre galaxie et contient environ un trillion d\'étoiles. Son immense taille apparente dans le ciel en fait une cible photographique spectaculaire.',
                'tips' => 'Très grande! Utilisez un temps de pose moyen pour capturer les détails du noyau et des bras spiraux.',
                'ra_hours' => 0,
                'ra_minutes' => 42,
                'ra_seconds' => 44.3,
                'dec_degrees' => 41,
                'dec_minutes' => 16,
                'dec_seconds' => 9,
                'best_months' => ['Sep', 'Oct', 'Nov', 'Déc'],
                'recommended_shots' => [
                    ['filter_name' => 'L', 'num' => 30, 'exposure' => 180, 'binning' => 1],
                    ['filter_name' => 'R', 'num' => 15, 'exposure' => 180, 'binning' => 1],
                    ['filter_name' => 'G', 'num' => 15, 'exposure' => 180, 'binning' => 1],
                    ['filter_name' => 'B', 'num' => 15, 'exposure' => 180, 'binning' => 1],
                ],
                'estimated_time' => '3h45min',
                'is_active' => true,
                'display_order' => 2,
            ],
            [
                'template_id' => 'm13',
                'name' => 'M13 - Grand Amas d\'Hercule',
                'type' => 'Amas Globulaire',
                'constellation' => 'Hercule',
                'difficulty' => 'beginner',
                'short_description' => 'L\'amas globulaire le plus spectaculaire de l\'hémisphère nord.',
                'full_description' => 'M13, le Grand Amas Globulaire d\'Hercule, est l\'un des amas globulaires les plus brillants et les plus beaux de l\'hémisphère nord. Contenant plusieurs centaines de milliers d\'étoiles anciennes concentrées dans une sphère de 145 années-lumière de diamètre, cet amas situé à 25 000 années-lumière offre un spectacle époustouflant.',
                'tips' => 'Objet compact et brillant. Excellent pour tester votre configuration.',
                'ra_hours' => 16,
                'ra_minutes' => 41,
                'ra_seconds' => 41.2,
                'dec_degrees' => 36,
                'dec_minutes' => 27,
                'dec_seconds' => 37,
                'best_months' => ['Avr', 'Mai', 'Juin', 'Jui', 'Aoû'],
                'recommended_shots' => [
                    ['filter_name' => 'L', 'num' => 30, 'exposure' => 120, 'binning' => 1],
                    ['filter_name' => 'R', 'num' => 10, 'exposure' => 120, 'binning' => 1],
                    ['filter_name' => 'G', 'num' => 10, 'exposure' => 120, 'binning' => 1],
                    ['filter_name' => 'B', 'num' => 10, 'exposure' => 120, 'binning' => 1],
                ],
                'estimated_time' => '2h',
                'is_active' => true,
                'display_order' => 3,
            ],
            [
                'template_id' => 'm27',
                'name' => 'M27 - Nébuleuse de l\'Haltère',
                'type' => 'Nébuleuse Planétaire',
                'constellation' => 'Renard',
                'difficulty' => 'beginner',
                'short_description' => 'Nébuleuse planétaire brillante et facile à imager.',
                'full_description' => 'M27, également connue sous le nom de Nébuleuse de l\'Haltère, est une nébuleuse planétaire brillante et l\'une des plus faciles à photographier. Elle représente les couches externes d\'une étoile mourante, éjectées dans l\'espace et illuminées par le noyau stellaire restant.',
                'tips' => 'Cible idéale pour débuter. Brillante et réactive à tous les filtres.',
                'ra_hours' => 19,
                'ra_minutes' => 59,
                'ra_seconds' => 36.3,
                'dec_degrees' => 22,
                'dec_minutes' => 43,
                'dec_seconds' => 16,
                'best_months' => ['Juin', 'Jui', 'Aoû', 'Sep'],
                'recommended_shots' => [
                    ['filter_name' => 'L', 'num' => 25, 'exposure' => 180, 'binning' => 1],
                    ['filter_name' => 'R', 'num' => 12, 'exposure' => 180, 'binning' => 1],
                    ['filter_name' => 'G', 'num' => 12, 'exposure' => 180, 'binning' => 1],
                    ['filter_name' => 'B', 'num' => 12, 'exposure' => 180, 'binning' => 1],
                ],
                'estimated_time' => '3h3min',
                'is_active' => true,
                'display_order' => 4,
            ],
            [
                'template_id' => 'm51',
                'name' => 'M51 - Galaxie du Tourbillon',
                'type' => 'Galaxie',
                'constellation' => 'Chiens de Chasse',
                'difficulty' => 'intermediate',
                'short_description' => 'Galaxie spirale avec compagnon, structure magnifique!',
                'full_description' => 'La Galaxie du Tourbillon (M51) est une superbe galaxie spirale vue de face, accompagnée de sa galaxie compagnon NGC 5195. Située à environ 23 millions d\'années-lumière, elle offre l\'un des plus beaux exemples de structure spirale visible depuis la Terre. Les bras spiraux bien définis en font une cible favorite des astrophotographes.',
                'tips' => 'Galaxie plus faible, privilégiez les nuits noires pour maximiser le contraste.',
                'ra_hours' => 13,
                'ra_minutes' => 29,
                'ra_seconds' => 52.7,
                'dec_degrees' => 47,
                'dec_minutes' => 11,
                'dec_seconds' => 43,
                'best_months' => ['Mar', 'Avr', 'Mai', 'Juin'],
                'recommended_shots' => [
                    ['filter_name' => 'L', 'num' => 40, 'exposure' => 240, 'binning' => 1],
                    ['filter_name' => 'R', 'num' => 20, 'exposure' => 240, 'binning' => 1],
                    ['filter_name' => 'G', 'num' => 20, 'exposure' => 240, 'binning' => 1],
                    ['filter_name' => 'B', 'num' => 20, 'exposure' => 240, 'binning' => 1],
                ],
                'estimated_time' => '6h40min',
                'is_active' => true,
                'display_order' => 5,
            ],
            [
                'template_id' => 'ngc7000',
                'name' => 'NGC 7000 - Nébuleuse North America',
                'type' => 'Nébuleuse',
                'constellation' => 'Cygne',
                'difficulty' => 'intermediate',
                'short_description' => 'Grande nébuleuse diffuse en forme de continent américain.',
                'full_description' => 'La Nébuleuse North America (NGC 7000) est une grande région d\'émission qui ressemble étonnamment au continent nord-américain. Située dans le Cygne à environ 2 600 années-lumière, cette nébuleuse étendue est idéale pour l\'imagerie à champ large, particulièrement avec des filtres à bande étroite.',
                'tips' => 'Idéale avec filtres à bande étroite (Ha, OIII). Très étendue, parfaite pour champ large.',
                'ra_hours' => 20,
                'ra_minutes' => 59,
                'ra_seconds' => 17.1,
                'dec_degrees' => 44,
                'dec_minutes' => 31,
                'dec_seconds' => 44,
                'best_months' => ['Juin', 'Jui', 'Aoû', 'Sep'],
                'recommended_shots' => [
                    ['filter_name' => 'Ha', 'num' => 30, 'exposure' => 300, 'binning' => 1],
                    ['filter_name' => 'OIII', 'num' => 20, 'exposure' => 300, 'binning' => 1],
                    ['filter_name' => 'R', 'num' => 15, 'exposure' => 180, 'binning' => 1],
                    ['filter_name' => 'G', 'num' => 15, 'exposure' => 180, 'binning' => 1],
                    ['filter_name' => 'B', 'num' => 15, 'exposure' => 180, 'binning' => 1],
                ],
                'estimated_time' => '7h15min',
                'is_active' => true,
                'display_order' => 6,
            ],
            [
                'template_id' => 'm57',
                'name' => 'M57 - Nébuleuse de l\'Anneau',
                'type' => 'Nébuleuse Planétaire',
                'constellation' => 'Lyre',
                'difficulty' => 'intermediate',
                'short_description' => 'Nébuleuse planétaire iconique en forme d\'anneau parfait.',
                'full_description' => 'La Nébuleuse de l\'Anneau (M57) est l\'une des nébuleuses planétaires les plus célèbres et photogéniques. Sa forme d\'anneau parfait est le résultat des couches externes d\'une étoile semblable au Soleil, expulsées à la fin de sa vie. Les filtres Ha et OIII révèlent des structures spectaculaires dans cette nébuleuse.',
                'tips' => 'Petite mais brillante. Les filtres Ha et OIII révèlent des détails spectaculaires.',
                'ra_hours' => 18,
                'ra_minutes' => 53,
                'ra_seconds' => 35.1,
                'dec_degrees' => 33,
                'dec_minutes' => 1,
                'dec_seconds' => 45,
                'best_months' => ['Mai', 'Juin', 'Jui', 'Aoû', 'Sep'],
                'recommended_shots' => [
                    ['filter_name' => 'L', 'num' => 30, 'exposure' => 180, 'binning' => 1],
                    ['filter_name' => 'Ha', 'num' => 20, 'exposure' => 300, 'binning' => 1],
                    ['filter_name' => 'OIII', 'num' => 20, 'exposure' => 300, 'binning' => 1],
                    ['filter_name' => 'R', 'num' => 10, 'exposure' => 180, 'binning' => 1],
                    ['filter_name' => 'G', 'num' => 10, 'exposure' => 180, 'binning' => 1],
                    ['filter_name' => 'B', 'num' => 10, 'exposure' => 180, 'binning' => 1],
                ],
                'estimated_time' => '5h30min',
                'is_active' => true,
                'display_order' => 7,
            ],
            [
                'template_id' => 'ic1396',
                'name' => 'IC 1396 - Nébuleuse de la Trompe d\'Éléphant',
                'type' => 'Nébuleuse',
                'constellation' => 'Céphée',
                'difficulty' => 'advanced',
                'short_description' => 'Région HII complexe avec piliers de création spectaculaires.',
                'full_description' => 'IC 1396 est une vaste région HII contenant la célèbre Trompe d\'Éléphant, un pilier de gaz et de poussière où se forment de nouvelles étoiles. Cette structure, similaire aux Piliers de la Création de M16, est spectaculaire en imagerie à bande étroite et nécessite un ciel sombre pour révéler tous ses détails.',
                'tips' => 'Projet avancé nécessitant filtres à bande étroite. Nuit noire fortement recommandée.',
                'ra_hours' => 21,
                'ra_minutes' => 39,
                'ra_seconds' => 0,
                'dec_degrees' => 57,
                'dec_minutes' => 30,
                'dec_seconds' => 0,
                'best_months' => ['Jui', 'Aoû', 'Sep', 'Oct'],
                'recommended_shots' => [
                    ['filter_name' => 'Ha', 'num' => 50, 'exposure' => 300, 'binning' => 1],
                    ['filter_name' => 'OIII', 'num' => 30, 'exposure' => 300, 'binning' => 1],
                    ['filter_name' => 'SII', 'num' => 30, 'exposure' => 300, 'binning' => 1],
                ],
                'estimated_time' => '9h10min',
                'is_active' => true,
                'display_order' => 8,
            ],
        ];

        foreach ($templates as $template) {
            TargetTemplate::create($template);
        }
    }
}
