<?php

return [
    [
        'slug' => 'm31-andromeda',
        'name' => 'M31 - Galaxie d\'Andromède',
        'type' => 'galaxy',
        'constellation' => 'Andromeda',
        'ra_hours' => 0.712,
        'dec_degrees' => 41.269,
        'magnitude' => 3.4,
        'best_months' => ['August', 'September', 'October', 'November'],
        'recommended_filters' => [
            ['filter' => 'L', 'exposure' => 300, 'frames' => 16],
            ['filter' => 'R', 'exposure' => 300, 'frames' => 12],
            ['filter' => 'G', 'exposure' => 300, 'frames' => 12],
            ['filter' => 'B', 'exposure' => 300, 'frames' => 12],
        ],
        'description' => 'Grande galaxie spirale très lumineuse, idéale pour un setup grand champ.',
        'thumbnail' => 'https://cdn.stellarloc.com/targets/m31.jpg',
    ],
    [
        'slug' => 'm42-orion-nebula',
        'name' => 'M42 - Nébuleuse d\'Orion',
        'type' => 'emission_nebula',
        'constellation' => 'Orion',
        'ra_hours' => 5.588,
        'dec_degrees' => -5.391,
        'magnitude' => 4.0,
        'best_months' => ['December', 'January', 'February', 'March'],
        'recommended_filters' => [
            ['filter' => 'L', 'exposure' => 180, 'frames' => 20],
            ['filter' => 'Ha', 'exposure' => 300, 'frames' => 12],
            ['filter' => 'OIII', 'exposure' => 300, 'frames' => 12],
        ],
        'description' => 'Nébuleuse brillante avec un cœur riche en détails et un large halo.',
        'thumbnail' => 'https://cdn.stellarloc.com/targets/m42.jpg',
    ],
    [
        'slug' => 'ic443-jellyfish',
        'name' => 'IC443 - Nébuleuse de la Méduse',
        'type' => 'supernova_remnant',
        'constellation' => 'Gemini',
        'ra_hours' => 6.338,
        'dec_degrees' => 22.514,
        'magnitude' => 10.0,
        'best_months' => ['January', 'February', 'March'],
        'recommended_filters' => [
            ['filter' => 'Ha', 'exposure' => 600, 'frames' => 10],
            ['filter' => 'OIII', 'exposure' => 600, 'frames' => 10],
            ['filter' => 'SII', 'exposure' => 600, 'frames' => 10],
        ],
        'description' => 'Reste de supernova riche en structures filamenteuses, idéal pour SHO.',
        'thumbnail' => 'https://cdn.stellarloc.com/targets/ic443.jpg',
    ],
    [
        'slug' => 'm13-hercules-cluster',
        'name' => 'M13 - Amas d\'Hercule',
        'type' => 'globular_cluster',
        'constellation' => 'Hercules',
        'ra_hours' => 16.695,
        'dec_degrees' => 36.462,
        'magnitude' => 5.8,
        'best_months' => ['May', 'June', 'July', 'August'],
        'recommended_filters' => [
            ['filter' => 'L', 'exposure' => 240, 'frames' => 18],
            ['filter' => 'R', 'exposure' => 240, 'frames' => 12],
            ['filter' => 'G', 'exposure' => 240, 'frames' => 12],
            ['filter' => 'B', 'exposure' => 240, 'frames' => 12],
        ],
        'description' => 'Amas globulaire dense nécessitant un suivi précis et un seeing correct.',
        'thumbnail' => 'https://cdn.stellarloc.com/targets/m13.jpg',
    ],
    [
        'slug' => 'ngc7000-north-america',
        'name' => 'NGC7000 - Nébuleuse North America',
        'type' => 'emission_nebula',
        'constellation' => 'Cygnus',
        'ra_hours' => 20.97,
        'dec_degrees' => 44.29,
        'magnitude' => 4.0,
        'best_months' => ['June', 'July', 'August', 'September'],
        'recommended_filters' => [
            ['filter' => 'Ha', 'exposure' => 300, 'frames' => 15],
            ['filter' => 'OIII', 'exposure' => 300, 'frames' => 10],
            ['filter' => 'SII', 'exposure' => 300, 'frames' => 10],
        ],
        'description' => 'Immense nébuleuse en émission, parfaite pour du narrowband grand champ.',
        'thumbnail' => 'https://cdn.stellarloc.com/targets/ngc7000.jpg',
    ],
    [
        'slug' => 'm81-bodes-galaxy',
        'name' => 'M81 - Galaxie de Bode',
        'type' => 'galaxy',
        'constellation' => 'Ursa Major',
        'ra_hours' => 9.933,
        'dec_degrees' => 69.065,
        'magnitude' => 6.9,
        'best_months' => ['February', 'March', 'April'],
        'recommended_filters' => [
            ['filter' => 'L', 'exposure' => 300, 'frames' => 18],
            ['filter' => 'R', 'exposure' => 300, 'frames' => 12],
            ['filter' => 'G', 'exposure' => 300, 'frames' => 12],
            ['filter' => 'B', 'exposure' => 300, 'frames' => 12],
        ],
        'description' => 'Galaxie spirale riche en détails, parfaite en binning 1 avec un seeing stable.',
        'thumbnail' => 'https://cdn.stellarloc.com/targets/m81.jpg',
    ],
];
